### ISSUE TITLE
Perlin noise tiles

### ISSUE THREAD

**Issue by serin-delaunay** [serin-delaunay/Wangscape#15]
Tile generation is now based on alpha-weighted combinations of input terrain tiles. Neither of the tileset generation methods so far considered in detail (splines and competitive floodfill) are really suitable for generating gradients at tile boundaries. Also, making splines generated tiles with complex boundary structures would be quite a complex task.

An alternative is to generate each corner's alpha mask directly. The edges must be fixed to ensure smooth tiling, and the middle must be stochastic (eg. Perlin noise) to ensure variety. A parameter should be made to control how much the tile is affected by the stochastic component. Perlin noise parameters would affect how rough or smooth the boundaries is. Post-processing should be applied to allow some terrain borders to be sharp, while others have gradients. The same post-processing would implement #14.

Once that dataflow is in place, it could be augmented with standard noise-combination methods (such as libtcod's heightmap tool, the libnoise examples, and SPARTAN by Paul Jeffries)

- [x] Add a Perlin noise generator (probably libnoise).
- [ ] libnoise is missing from NuGet; maybe add it? (Making native NuGet packages in VS 2015 is not well supported)
- [x] Remove border specifications based on offset, derivative pairs.
- [x] Blend/Select module
  - [x] MovingScaleBias module (fading as distance from corner increases)
    - [x] Blend/Select module
      - [ ] anything
        - [x] reuse with same seed for borders with the same horizontal terrain pair
        - [ ] read specification from options file (#28)
        - [x] translate y by -1 if horizontal border is at the bottom
      - [ ] anything
        - [x] reuse with same seed for borders with the same vertical terrain pair
        - [ ] read specification from options file (#28)
        - [x] translate x by -1 if vertical border is on the right
      - [x] CornerCombiner module:
        - [x]  0.5 along diagonal, ~1 along x edge, ~-1 along y edge, faster transition closer to active corner
          - [x] negative x quadrant if vertical border is on the right
          - [x] negative y quadrant if horizontal border is at the bottom
  - [ ] anything
    - [x] reuse with different seed for all corners with the same terrain
    - [ ] read specification from options file (#28)
  - [x] Edge-favouring mask: L^p distance from (0.5,0.5), raised to power q, scaled and clamped to [-1,1]
- [x] Convert float weights to UInt8 alpha masks (expansion: #37)

**Comment by serin-delaunay** [comment]
Got the first output tiles from this method! ![perlin1](https://cloud.githubusercontent.com/assets/15715657/21297825/fe83705e-c57e-11e6-94f6-22d4308f6a80.PNG)

Still a few kinks to work out. The bright patches are probably a UInt8 arithmetic overflow, and the tiles all look too similar in the centre (an even blend of the two component terrains). The tiling isn't seamless in a lot of cases.

**Comment by serin-delaunay** [comment]
The version with sharp borders looks much nicer:

![perlin-hard](https://cloud.githubusercontent.com/assets/15715657/21312600/f556547c-c5e4-11e6-9116-507af0b9f5c2.PNG)

The borders don't match, though.

**Comment by serin-delaunay** [comment]
The core of Perlin tileset generation is complete now, so I'm going to close this and split the remaining concerns into new issues: #28, #37, #39, #38.
